= SuaderoSolar 🌮
:icons: font
:sectanchors:
// Enable fancy admonition icons on GH
ifdef::env-github[]
:tip-caption: :bulb:
:toc:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Contributing with Git ❓

IMPORTANT: Use terminal git, not the bloated GUI version. 

The workflow is as follows:

. Update (or clone) the local repo
. Create new local issue branch
. Hack away
. Commit and push to a new server branch
. Create pull request
. (Solve feedback)
. Delete local branch

If you don't have git and/or hub, run in Powershell with admin rights:

[source, powershell]
----
Set-ExecutionPolicy AllSigned
----

then

[source, powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install git hub -y
----
Else, download https://git-scm.com/downloads[git] and https://github.com/github/hub/releases[hub]

. Clone if this is the first time modifying the codebase.
+
[source, powershell]
----
git clone https://github.com/Mauville/SuaderoSolar.git
cd SuaderoSolar
git fetch origin
git checkout -b dev origin/dev
----
+
. Create new feature branch
+
[source, powershell]
----
git checkout -b {your-name}
----
+
. Begin making changes. . Once finished, add changes and create a commit.
IMPORTANT: Create a lot of commits between medium changes such as functions and big control structures.
+
IMPORTANT: The commit message (the string between the quotes) should describe what you did.
+
[source, powershell]
----
git add *
git commit -m 'COMMIT MESSAGE'
----
+
. Push & create a pull request with necessary info.
+
NOTE: You can get the branch name using `git branch`
+
[source, powershell]
----
git push --set-upstream origin {BRANCH_NAME}
hub pull-request -m "{Main Feature}" -m "{Description of feature}" -b Mauville:dev
----
+
At this point, you should wait for feedback. If there are changes to make, add, commit and push again but do not create another PR.
+
. If your changes got accepted and merged into `dev`, delete your feature branch from local so next time you work you start clean.
+
[source, powershell]
----
git checkout dev
git branch -d <branch name>
----
+
. When you are ready to tackle another issue, be sure to get the latest changes before you create a new feature branch from `dev` (This means starting from Step 2.
+
[source, powershell]
----
git pull
----



== Setup, Run, Build 🛠

You need to download some dependencies to begin working on this!

First, https://nodejs.org/en/download/[install Node.js.]
If you have https://chocolatey.org/[choco] installed (you have if you followed the setup for the git installation below), you can run:

[source, powershell]
----
# In the project directory
cinst node -y
refreshenv
----

Then, install the dependencies. **It should finish with no errors but some warning are perfectly fine.**

[source, powershell]
----
# In the project directory
npm i 
----
For performance reasons, production builds of the site are not commited. You will need to build the site for your local version.
[source, powershell]
----
# In the project directory
npm run build
----

IMPORTANT: Since we are using APIs, keys need to be stored safely. Ask the project manager for the .env file and put in in the root. The project won't run without them.

To run the website as a whole, mount the server.
[source, powershell]
----
# In the project directory after the dependency installs
npm run server
----

=== Front-End

When modifying React front-end, you can mount a miniserver to preview it on the browser
[source, powershell]
----
# In the project directory after the dependency installs
npm start
----



== Important Resources 📖

* For the backend tutorials, https://www.github.com/Mauville/GoodExpress[use these], here you can find almost everything on how the backend works.

* For how to work on the front-end, you can watch the first hour of https://www.youtube.com/watch?v=zIY87vU33aA[this video] 

* Use https://material-ui.com[Material-UI] for the front-end.

=== Front-end Ideas 💡
====
Forms UX:

https://uxdesign.cc/the-ux-behind-designing-better-forms-d6ebe7a817d2

https://uxdesign.cc/11-form-design-guidelines-4b2f1c659414

https://cxl.com/blog/mobile-forms/

Components for forms:

https://styled-components.com/

Form persistence (Antifuckups):

https://garlicjs.org/

Form Validation:

https://jaredpalmer.com/formik/docs/overview 

https://dev.to/finallynero/react-form-using-formik-material-ui-and-yup-2e8h

Form Autofilling:

https://medium.com/dev-channel/improving-mobile-web-conversions-just-by-optimizing-web-forms-1d846bed42f

https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

Automatic city filling:

https://blog.logrocket.com/detect-location-and-local-timezone-of-users-in-javascript-3d9523c011b9/

Use steppers for progress tracking:

https://material-ui.com/components/steppers/

Use input spinners for the appliances numbers:

https://www.jqueryscript.net/blog/best-number-input-spinner.html

https://shaack.com/projekte/bootstrap-input-spinner/

Tesseract.js to OCR the bill and get data (Optional but a biiiiig plus):

https://blog.logrocket.com/how-to-extract-text-from-an-image-using-javascript-8fe282fb0e71/

https://medium.com/panya-studio-engineering/eliminating-manual-data-entry-using-ocr-to-convert-images-to-text-tesseract-js-react-1099d20a4f4

Express Tuts:

https://github.com/Mauville/GoodExpress

====

=== Setup VSCode for programming efficiency 😎
[source, powershell]
----
code --install-extension dbaeumer.vscode-eslint
----
In VSCode, CTRL + , to open User Settings and add this to enable auto-prettify on save:
[source, json]
----
{
    "editor.formatOnSave": true,
    "javascript.format.enable": false,
    "prettier.eslintIntegration": true
}
----

~Mauville
